aws_profile: "default"
aws_region: "us-east-1"
aws_account_id: "429104603739"

cluster_name: "devops-ha-eks"
vpc_id: "vpc-02b2c1ffe9d39f9b4"

bastion_public_ip: "98.92.153.173"
bastion_private_ip: "10.0.10.217"
bastion_key_path: "/home/ahmedrabie/.ssh/devops-ha-eks-bastion-key.pem"

ecr_repository_name: "digipipeline-app"
ecr_repository_url: "429104603739.dkr.ecr.us-east-1.amazonaws.com/digipipeline-app"

jenkins_url: "http://34.212.70.138:8080"
jenkins_controller_public_ip: "34.212.70.138"
jenkins_controller_private_ip: "10.20.10.65"
jenkins_agent_private_ips:
  - "10.20.10.40"
  - "10.20.20.157"

aws_lbc_policy_name: "AWSLoadBalancerControllerIAMPolicy-devops-ha-eks"
aws_lbc_role_name: "AmazonEKSLoadBalancerControllerRole-devops-ha-eks"
aws_lbc_namespace: "kube-system"
aws_lbc_service_account_name: "aws-load-balancer-controller"

karpenter_namespace: "kube-system"
karpenter_service_account_name: "karpenter"
karpenter_controller_role_arn: "arn:aws:iam::429104603739:role/KarpenterControllerRole-devops-ha-eks"
karpenter_node_role_name: "devops-ha-eks-node-role"
karpenter_ec2nodeclass_name: "default"
karpenter_nodepool_name: "default"
