[bastion]
devops-bastion ansible_host=44.199.207.93 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ahmedrabie/.ssh/devops-ha-eks-bastion-key.pem

[jenkins_controller]
jenkins-controller ansible_host=35.92.1.242 ansible_user=ec2-user ansible_ssh_private_key_file=/home/ahmedrabie/.ssh/devops-ha-eks-bastion-key.pem

[jenkins_agents]
jenkins-agent-1 ansible_host=10.20.10.191 ansible_user=ec2-user ansible_ssh_private_key_file=/home/ahmedrabie/.ssh/devops-ha-eks-bastion-key.pem ansible_ssh_common_args='-o ProxyJump=ec2-user@35.92.1.242 -o StrictHostKeyChecking=no'
jenkins-agent-2 ansible_host=10.20.20.49 ansible_user=ec2-user ansible_ssh_private_key_file=/home/ahmedrabie/.ssh/devops-ha-eks-bastion-key.pem ansible_ssh_common_args='-o ProxyJump=ec2-user@35.92.1.242 -o StrictHostKeyChecking=no'
