---
- name: Create base namespaces
  hosts: dev
  gather_facts: false

  tasks:
    - name: Create namespaces
      ansible.builtin.shell: |
        kubectl create namespace {{ item }} --dry-run=client -o yaml | kubectl apply -f -
      loop:
        - apps
        - argocd
        - monitoring
      changed_when: false
